nodeLinker: node-modules

defaultLanguageName: "node"

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAuthToken: DDE2212E-8740-4148-8E9E-F460A46DA035

yarnPath: .yarn/releases/yarn-3.0.2.cjs
