export const ADD_TRANSLATE_MULTILINE = 'saga/ADD_TRANSLATE_MULTILINE';
export const CREATE_TRANSLATE_MULTILINE = 'saga/CREATE_TRANSLATE_MULTILINE';
export const UPDATE_TRANSLATE_MULTILINE = 'saga/UPDATE_TRANSLATE_MULTILINE';
